### PR TITLE
edited login.jsp to include password text field

### PR DESCRIPTION
**Pull request by TsueiCat**
I edited the login.jsp file to include the 'password' label and its corresponding text field.
Signed-off-by: TsueiCat <catherinetsuei617@gmail.com>
image

### CODE REVIEW

**Review by tharminhtet — APPROVED** [review]
All good!

**Comment by sherryx8** [comment]
good!

**Review by sherryx8 — APPROVED** [review]
good

**Review by sgoya — APPROVED** [review]

**Comment by TsueiCat** [comment]
Thanks for the reviews! I'm merging this now.

**Pull request merged**
