### PR TITLE
Private Messaging Complete

### PR DESCRIPTION
**Pull request by sherryx8**
Added user verification in chatServlet so that unauthorized user cannot access a private conversation with a link. Also made changes in Conversation Servlet so that private conversations won't be listed. 

**_Connected pieces needed for Private Messaging. Also made sure private messages don't show up on user profile. (These new changes are in ItalicBold)_**

Here are the sections and files that you should review: 

-------------------------------------------------------
Conversation:
- checkIfParticipant(String userName)
- **_getConversationWithId(UUID Id)_**

ChatServlet:
- doGet() lines 122-130

ChatServletTest:
- testDoGet_accessUserPrivateConversation()
- testDoGet_noAccessUserPrivateConversation()

ConversationStore:
- getAllPublicConversations()

ConversationStoreTest:
- testGetAllPublicConversations()

ConversationServlet:
- line 74 getAllConversations() -> getAllPublicConversations()
- **_line 106, 116, 135 conversationPrivacy_**

MessageStore
- **_getMessagesForUser()_**

### CODE REVIEW

**Review by tharminhtet — APPROVED** [review]
Good work especially with the testing!

**Review by tharminhtet — APPROVED** [review]
Thanks for the notes of your changes. I should take an example of that.

**Review by tharminhtet — APPROVED** [review]
Everything looks good!

**Review by TsueiCat — APPROVED** [review]
Job well done!!!! I noticed that the User class field userContactCache is not being used since there are checks to see if the conversation title has been taken. Would it be better to delete the field?

**Pull request merged**
